# TODO: Rename this file from 'docker-compose..yaml' to 'docker-compose.yaml' (remove double dots)
# TODO: Create Dockerfile - referenced by 'build: .' but doesn't exist
# TODO: Add database service (PostgreSQL) - settings.py requires it but it's not in docker-compose

version: "3.9"

services:

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  web:
    build: .  # TODO: Create Dockerfile for this to work
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      REDIS_HOST: redis
      REDIS_PORT: 6379
